# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisineID', models.AutoField(primary_key=True, serialize=False)),
                ('Rcuisine', models.CharField(max_length=30, verbose_name=b'cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='Geoplace',
            fields=[
                ('placeID', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.IntegerField(verbose_name=b'latitude')),
                ('longitude', models.IntegerField(verbose_name=b'longitude')),
                ('the_geom_meter', models.CharField(max_length=50, verbose_name=b'geom_meter')),
                ('name', models.CharField(max_length=50, verbose_name=b'name')),
                ('address', models.CharField(max_length=50, verbose_name=b'address')),
                ('city', models.CharField(max_length=10, verbose_name=b'city')),
                ('state', models.CharField(max_length=10, verbose_name=b'state')),
                ('country', models.CharField(max_length=10, verbose_name=b'country')),
                ('fax', models.IntegerField(verbose_name=b'fax')),
                ('zip', models.IntegerField(verbose_name=b'zip')),
                ('alcohol', models.CharField(max_length=20, verbose_name=b'alcohol')),
                ('smoking_area', models.CharField(max_length=30, verbose_name=b'smoking')),
                ('dress_code', models.CharField(max_length=10, verbose_name=b'dress code')),
                ('accessibility', models.CharField(max_length=30, verbose_name=b'accessibility')),
                ('price', models.CharField(max_length=10, verbose_name=b'price')),
                ('url', models.CharField(max_length=100, verbose_name=b'url')),
                ('Rambience', models.CharField(max_length=10, verbose_name=b'rambience')),
                ('franchise', models.CharField(max_length=1, verbose_name=b'franchise')),
                ('area', models.CharField(max_length=10, verbose_name=b'area')),
                ('other_services', models.CharField(max_length=10, verbose_name=b'otherservices')),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('hourID', models.AutoField(primary_key=True, serialize=False)),
                ('hours', models.CharField(max_length=20, verbose_name=b'hours')),
                ('days', models.CharField(max_length=5, verbose_name=b'days')),
                ('placeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Geoplace', verbose_name=b'place_id')),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('parkingID', models.AutoField(primary_key=True, serialize=False)),
                ('parking_lot', models.CharField(max_length=20, verbose_name=b'parking')),
                ('placeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Geoplace', verbose_name=b'place_id')),
            ],
        ),
        migrations.CreateModel(
            name='ratingFinal',
            fields=[
                ('ratingID', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(verbose_name=b'rating')),
                ('food_rating', models.IntegerField(verbose_name=b'food_rating')),
                ('service_rating', models.IntegerField(verbose_name=b'service_rating')),
                ('placeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Geoplace', verbose_name=b'place_id')),
            ],
        ),
        migrations.CreateModel(
            name='userCuisine',
            fields=[
                ('ucID', models.AutoField(primary_key=True, serialize=False)),
                ('Rcuisine', models.CharField(max_length=30, verbose_name=b'cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.IntegerField(verbose_name=b'latitude')),
                ('longitude', models.IntegerField(verbose_name=b'longitude')),
                ('the_geom_meter', models.CharField(max_length=50, verbose_name=b'geom_meter')),
                ('smoker', models.BooleanField(verbose_name=b'smoker')),
                ('drink_level', models.CharField(max_length=20, verbose_name=b'drink_level')),
                ('dress_preference', models.CharField(max_length=30, verbose_name=b'dress_preference')),
                ('ambience', models.CharField(max_length=20, verbose_name=b'ambience')),
                ('transport', models.CharField(max_length=10, verbose_name=b'transport')),
                ('marital_status', models.CharField(max_length=10, verbose_name=b'martial')),
                ('hijos', models.CharField(max_length=10, verbose_name=b'hijos')),
                ('birth_year', models.CharField(max_length=20, verbose_name=b'birth_year')),
                ('interest', models.CharField(max_length=30, verbose_name=b'interest')),
                ('personality', models.CharField(max_length=50, verbose_name=b'personality')),
                ('religion', models.CharField(max_length=10, verbose_name=b'religion')),
                ('activity', models.CharField(max_length=20, verbose_name=b'activity')),
                ('color', models.CharField(max_length=10, verbose_name=b'color')),
                ('weight', models.FloatField(verbose_name=b'weight')),
                ('budget', models.CharField(max_length=10, verbose_name=b'budget')),
                ('height', models.FloatField(verbose_name=b'height')),
            ],
        ),
        migrations.AddField(
            model_name='usercuisine',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.userProfile', verbose_name=b'user_id'),
        ),
        migrations.AddField(
            model_name='ratingfinal',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.userProfile', verbose_name=b'user_id'),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='placeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Geoplace', verbose_name=b'place_id'),
        ),
    ]
