# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0002_cuisinelabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoker', models.BooleanField(default=False, verbose_name=b'smoker')),
                ('drink_level', models.CharField(max_length=20, null=True, verbose_name=b'drink_level')),
                ('marital_status', models.CharField(max_length=10, null=True, verbose_name=b'martial')),
                ('hijos', models.CharField(max_length=10, null=True, verbose_name=b'hijos')),
                ('birth_year', models.CharField(max_length=20, null=True, verbose_name=b'birth_year')),
                ('interest', models.CharField(max_length=30, null=True, verbose_name=b'interest')),
                ('personality', models.CharField(max_length=50, null=True, verbose_name=b'personality')),
                ('religion', models.CharField(max_length=10, null=True, verbose_name=b'religion')),
                ('activity', models.CharField(max_length=20, null=True, verbose_name=b'activity')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'user_id')),
            ],
        ),
    ]
